
public enum Item {
	
	BANANA, MACA, LARANJA, PESSEGO, ARROZ, FEIJAO, QUEIJO, VAZIO,MACARRAO,TOMATE,CEBOLA,
	UVA,BATATA,FARINHA,MANTEIGA,LEITE,BISCOITO,CHOCOLATE,REFRIGERANTE,IORGUTE,SORVETE;

}
