package LogicaDoJogo;

public enum Item {
	 LEITE, BISCOITO, UVA, REFRIGERANTE, IOGURTE, SORVETE, TOMATE ,CEBOLA ,CAJU, BATATA , FARINHA , MANTEIGA,
	ARROZ,FEIJÃO, QUEIJO, MACARRÃO, CUSCUZ,	BOLACHA, BANANA , LARANJA , MAÇÃ, AMEIXA, OVO, CHOCOLATE, VAZIO, ABACAXI, ABACATE ;
	
}
